#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    background = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_display_mode = false
    default_indent = 4

    enable_neomake = 1
    # enable_ale = 1
    filemanager = "nerdtree"

    enable_ycm = 1

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"


[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = 'ale'
open_list = 1
cpp_clang_options = '-std=c++17 -isystem /usr/include/c++/8 -I/usr/include/c++/8 -I/usr/local/include -I/usr/include -I/usr/include/x86_64-linux-gnu'
# cpp_gcc_options = '-std=c++17 -isystem /usr/include/c++/8 -I/usr/include/c++/8 -I/usr/local/include -I/usr/include -I/usr/include/x86_64-linux-gnu'

[[custom_plugins]]
name = 'tenfyzhong/CompleteParameter.vim'

[[custom_plugins]]
name = 'jiangmiao/auto-pairs'


[[custom_plugins]]
name = 'octol/vim-cpp-enhanced-highlight'
merge = 0
on_ft = ['cc', 'cpp', 'h', 'hpp']

[[custom_plugins]]
name = 'erickzanardo/vim-xclip'
